### ISSUE TITLE
AptxHD for OneUI

### ISSUE THREAD

**Issue by pigxiang** [multiwirth/aptx-magisk-module-armv7#5]
Hi
Is it possible to enable Aptx HD or Aptx Adaptive on Samsung Galaxy devcies with OneUI?

**Comment by multiwirth** [comment]
APTX and APTX-HD are officially supported since android oreo, so if samsung doesn´t use their own heavily modified bluetooth stack, chances are high these blobs will work for OneUI.
Maybe just give it a try?
You can always remove the magisk module in case it doesn´t work, it doesn´t do permanent changes to your system.
Make sure you have TWRP-recovery installed, in case you can´t boot your OS and have to remove the module manually before booting.

Unfortunately i don´t have any recent samsung device, nor do i have the skill to provide a patched bluetooth stack for those devices, let alone the complexity of supporting different OneUI configurations on different models.
I also can´t test this module on those devices.
